FROM eclipse-temurin:17

LABEL mentainer="admint@hihghway65.com"

WORKDIR /app

COPY target/springboot-rest-crud-0.0.1-SNAPSHOT.jar /app/springboot-restful-webservices.jar

ENTRYPOINT ["java", "-jar", "springboot-restful-webservices.jar"]